wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      4: 3.7.9
      5: 0.10.21
      8:
      - 1
      - 5
activation_fn:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.01
loss:
  desc: null
  value: cross-entropy
no_epochs:
  desc: null
  value: 10
no_hidden_layers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: momentum
regularisation:
  desc: null
  value: L2
size_hidden_layer:
  desc: null
  value: 128
weight_decay:
  desc: null
  value: 0.0005
weight_initialisation:
  desc: null
  value: xavier
